version: "3"
services:
  # MySQL
  db:
    image: mysql:8.0.22
    platform: linux/amd64
    ports:
      - "13306:3306"
    container_name: mysql_host
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
